version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Maps port 6379 on the host to port 6379 on the container
    volumes:
      - redis_data:/data  # Persist data between container restarts

volumes:
  redis_data:

