version: '3.7'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: random_values_db
    ports:
      - "5432:5432"

  node_server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    environment:
      - DATABASE_URL=postgres://postgres:password@timescaledb:5432/random_values_db

