apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihatemoney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ihatemoney
  template:
    metadata:
      labels:
        app: ihatemoney
    spec:
      containers:
      - name: ihatemoney
        image: ihatemoney/ihatemoney
        ports:
        - containerPort: 8000

